version: '3'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./error.log:/var/log/mysql/error.log
    ports:
      - 3307:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1595@!
      - MYSQL_DATABASE=pinomaker
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwer1595@!
      - TZ=Asia/Seoul