version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./error.log:/var/log/mysql/error.log
    ports:
      - 3307:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1595@!
      - MYSQL_DATABASE=temporence_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwer1595@!
      - TZ=Asia/Seoul
    networks:
      - my-network

  myapp:
    image: pinomaker/mars-game:latest-arm64
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/temporence_dev?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwer1595@!
      - SPRING_REDIS_HOST=redis
    networks:
      - my-network

  cms:
    image: pinomaker/pinomaker:latest
    depends_on:
      - mysql
      - redis
    ports:
      - 9000:9000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/temporence_dev?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=qwer1595@!
      - SPRING_REDIS_HOST=redis

networks:
  my-network: